2020-05-10 01:55:59,926 INFO: Qontroverse startup [in /Users/erickiarie/PycharmProjects/Qontroverse/app/__init__.py:89]
2020-05-11 11:00:11,015 INFO: Qontroverse startup [in /Users/erickiarie/PycharmProjects/Qontroverse/app/__init__.py:89]
2020-05-11 11:00:23,134 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/email.py", line 13, in send_email
    html_content=html_body)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 74, in __init__
    self.add_content(html_content, MimeType.html)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 724, in add_content
    if content.mime_type == "text/plain":
AttributeError: 'unicode' object has no attribute 'mime_type'
2020-05-11 11:01:06,944 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/email.py", line 13, in send_email
    html_content=str(html_body))
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 74, in __init__
    self.add_content(html_content, MimeType.html)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 724, in add_content
    if content.mime_type == "text/plain":
AttributeError: 'unicode' object has no attribute 'mime_type'
2020-05-11 11:03:51,939 ERROR: Exception on /auth/reset_password_request [POST] [in /Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/auth/email.py", line 14, in send_password_reset_email
    user=user, token=token))
  File "/Users/erickiarie/PycharmProjects/Qontroverse/app/email.py", line 13, in send_email
    subject=subject,
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 74, in __init__
    self.add_content(html_content, MimeType.html)
  File "/Users/erickiarie/Desktop/blog/microblog/env/lib/python2.7/site-packages/sendgrid/helpers/mail/mail.py", line 724, in add_content
    if content.mime_type == "text/plain":
AttributeError: 'unicode' object has no attribute 'mime_type'
2020-05-11 11:04:08,510 INFO: Qontroverse startup [in /Users/erickiarie/PycharmProjects/Qontroverse/app/__init__.py:89]
2020-05-11 11:05:21,196 INFO: Qontroverse startup [in /Users/erickiarie/PycharmProjects/Qontroverse/app/__init__.py:89]
2020-05-11 11:07:22,560 INFO: Qontroverse startup [in /Users/erickiarie/PycharmProjects/Qontroverse/app/__init__.py:89]
